http_server:
  address: ":8081"
  timeout: "2s"
jwt:
  issuer: auth-service
  expires_in: 12h
#  public_key_path: "jwtRS256.key.pub"
#  private_key_path: "jwtRS256.key"
  public_key_path: "public_key.pem"
  private_key_path: "private_key.pem"